name: Echo Commits on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  echo_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        if: ${{ github.event.pull_request.merged }}
        run: |
          echo "The following commits were merged:"
          git log --pretty=format:"%h %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
