name: My Custom Workflow

on:
  push:
    branches:
      - "*"

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: exit
        run: |
          echo "CHANGE_FILE=uiHome" >> $GITHUB_ENV
      - name: this not exec
        if: env.CHANGE_FILE == 'ui'
        run: |
          echo 'not exec'
          git log
      - name: this exec
        if: env.CHANGE_FILE == 'uiHome'
        run: |
          echo 'not exec'
          git log
